name: Add issues to PowerShell Modules project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project
        with:
          project-url: https://github.com/users/devynspencer/projects/10
          github-token: ${{ secrets.PAT_GITHUB_ACTIONS_POWERSHELL }}
          labeled: documentation, bug, enhancement, function, tests
          label-operator: OR
