name: Add issues to PowerShell Modules project

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  add-to-project:
    name: Add issue [${{ github.event.issue.number }}] ${{ github.event.issue.title }} to project
    runs-on: ubuntu-latest
    environment: powershell
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/devynspencer/projects/10 # PowerShell Modules
          github-token: ${{ secrets.CLASSIC_TOKEN }}
          labeled: documentation, bug, enhancement, function, tests
          label-operator: OR
          
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/devynspencer/projects/16 # Workflow Automation
          github-token: ${{ secrets.CLASSIC_TOKEN }}
          labeled: automation, workflow, action, webhook
          label-operator: OR
