name: Add issues to PowerShell Modules project

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  add-to-project:
    name: Add issue [${{ github.event.issue.number }}] ${{ github.event.issue.title }} to project
    runs-on: ubuntu-latest
    environment: powershell
    steps:
      - name: Add issue [${{ github.event.issue.number }}] to PowerShell Modules project
        if: github.event.issue.state != 'closed'
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/devynspencer/projects/10 # PowerShell Modules
          github-token: ${{ secrets.CLASSIC_TOKEN }}
          labeled: documentation, bug, enhancement, function, tests
          label-operator: OR
          
      - name: Set fields for project card ${{ github.event.issue.title }}
        if: |
          github.event.issue.state != 'closed'
          contains(github.event.issue.labels.*.name, 'item: chat bot') ||
          contains(github.event.issue.labels.*.name, 'item: documentation') ||
          contains(github.event.issue.labels.*.name, 'item: function') ||
          contains(github.event.issue.labels.*.name, 'item: module') ||
          contains(github.event.issue.labels.*.name, 'item: script') ||
          contains(github.event.issue.labels.*.name, 'item: unit test') ||
          contains(github.event.issue.labels.*.name, 'item: integration test') ||
          contains(github.event.issue.labels.*.name, 'type: bug') ||
          contains(github.event.issue.labels.*.name, 'type: enhancement') ||
          contains(github.event.issue.labels.*.name, 'type: feature request')
        uses: endbug/project-fields@v2
        with:
          project_url: https://github.com/users/devynspencer/projects/10 # PowerShell Modules
          operation: set
          fields: Date Added,Status
          values: ${{ github.event.issue.created_at }},Backlog
          github_token: ${{ secrets.CLASSIC_TOKEN }}

      - name: Add issue [${{ github.event.issue.number }}] to Workflow Automation project
        if: github.event.issue.state != 'closed'
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/devynspencer/projects/16 # Workflow Automation
          github-token: ${{ secrets.CLASSIC_TOKEN }}
          labeled: automation, workflow, action, webhook, template
          label-operator: OR

      - name: Set fields for project card ${{ github.event.issue.title }}
        if: |
          github.event.issue.state != 'closed'
          contains(github.event.issue.labels.*.name, 'item: webhook') ||
          contains(github.event.issue.labels.*.name, 'item: custom action') ||
          contains(github.event.issue.labels.*.name, 'item: workflow') ||
          contains(github.event.issue.labels.*.name, 'item: template')
        uses: endbug/project-fields@v2
        with:
          project_url: https://github.com/users/devynspencer/projects/16 # PowerShell Modules
          operation: set
          fields: Date Added,Status
          values: ${{ github.event.issue.created_at }},Backlog
          github_token: ${{ secrets.CLASSIC_TOKEN }}
